"""Type stubs for larp.field.geometry (compiled from geometry.pyx)."""

from __future__ import annotations

from typing import Any, ClassVar

import numpy as np
import numpy.typing as npt

from larp.types import Point, RGeoJSONObject

FloatArray = npt.NDArray[np.float64]

class RGJGeometry:
    RGJType: ClassVar[str | None]

    coordinates: FloatArray
    repulsion: FloatArray
    inv_repulsion: FloatArray
    eye_repulsion: FloatArray
    grad_matrix: FloatArray
    properties: dict
    bbox: FloatArray

    def __init__(
        self,
        coordinates: FloatArray | list[Point] | Point,
        repulsion: FloatArray | None = ...,
        properties: dict | None = ...,
        optional_dim: int = ...,
        **kwargs: Any,
    ) -> None: ...
    def set_coordinates(self, new_coords: Any) -> None: ...
    def set_repulsion(self, new_repulsion: Any) -> None: ...
    def get_dist_matrix(self, scaled: bool = ..., inverted: bool = ...) -> FloatArray: ...
    def get_center_point(self) -> FloatArray: ...
    def in_bbox(self, x: Point) -> bool: ...
    def repulsion_vector(self, x: FloatArray, **kwargs: Any) -> FloatArray: ...
    def squared_dist(self, x: FloatArray, scaled: bool = ..., inverted: bool = ..., **kwargs: Any) -> FloatArray: ...
    def contact_point(self, x: FloatArray, **kwargs: Any) -> FloatArray: ...
    def gradient(self, x: FloatArray, **kwargs: Any) -> FloatArray: ...
    def eval(self, x: FloatArray) -> FloatArray: ...
    def toRGeoJSON(self) -> RGeoJSONObject: ...
    @property
    def __geo_interface__(self) -> RGeoJSONObject: ...

class MultiRGJGeometry(RGJGeometry):
    def repulsion_vector(self, x: FloatArray, min_dist_select: bool = ..., **kwargs: Any) -> FloatArray: ...
    def contact_point(self, x: FloatArray, min_dist_select: bool = ..., **kwargs: Any) -> FloatArray: ...

class PointRGJ(RGJGeometry):
    RGJType: ClassVar[str]
    def repulsion_vector(self, x: FloatArray, **kwargs: Any) -> FloatArray: ...

class LineStringRGJ(MultiRGJGeometry):
    RGJType: ClassVar[str]
    points_in_line_pair: FloatArray
    lines_n: int

    def __init__(self, coordinates: FloatArray, repulsion: FloatArray | None = ..., **kwargs: Any) -> None: ...
    def set_coordinates(self, new_coords: Any) -> None: ...
    def repulsion_vector(self, x: FloatArray, min_dist_select: bool = ..., **kwargs: Any) -> FloatArray: ...

class MultiLineStringRGJ(LineStringRGJ):
    RGJType: ClassVar[str]
    coordinates: list[FloatArray]  # type: ignore[assignment]

    def __init__(
        self,
        coordinates: list[FloatArray],
        repulsion: FloatArray | None = ...,
        properties: dict | None = ...,
        optional_dim: int = ...,
        **kwargs: Any,
    ) -> None: ...
    def set_coordinates(self, new_coords: Any) -> None: ...
    def get_center_point(self) -> FloatArray: ...

class MultiPointRGJ(MultiRGJGeometry):
    RGJType: ClassVar[str]
    def __init__(self, coordinates: FloatArray, repulsion: FloatArray | None = ..., **kwargs: Any) -> None: ...
    def in_bbox(self, x: Point) -> bool: ...
    def repulsion_vector(self, x: FloatArray, min_dist_select: bool = ..., **kwargs: Any) -> FloatArray: ...

class PolygonRGJ(RGJGeometry):
    RGJType: ClassVar[str]
    rings: list[FloatArray]
    points_in_line_pair: FloatArray
    metric: FloatArray

    def __init__(
        self,
        coordinates: FloatArray | list[Any],
        repulsion: FloatArray | None = ...,
        properties: dict | None = ...,
        optional_dim: int = ...,
        **kwargs: Any,
    ) -> None: ...
    def set_coordinates(self, new_coords: Any) -> None: ...
    def set_repulsion(self, new_repulsion: Any) -> None: ...
    def in_bbox(self, x: Point) -> bool: ...
    def repulsion_vector(self, x: FloatArray, min_dist_select: bool = ..., **kwargs: Any) -> FloatArray: ...
    def toRGeoJSON(self) -> RGeoJSONObject: ...

class MultiPolygonRGJ(MultiRGJGeometry):
    RGJType: ClassVar[str]
    polygons: list[PolygonRGJ]
    points_in_line_pair: FloatArray

    def __init__(
        self,
        coordinates: list[Any],
        repulsion: FloatArray | None = ...,
        properties: dict | None = ...,
        optional_dim: int = ...,
        **kwargs: Any,
    ) -> None: ...
    def set_coordinates(self, new_coords: Any) -> None: ...
    def in_bbox(self, x: Point) -> bool: ...
    def get_center_point(self) -> FloatArray: ...
    def repulsion_vector(self, x: FloatArray, min_dist_select: bool = ..., **kwargs: Any) -> FloatArray: ...
    def toRGeoJSON(self) -> RGeoJSONObject: ...

class GeometryCollectionRGJ(MultiRGJGeometry):
    RGJType: ClassVar[str]
    rgjs: list[RGJGeometry]
    inv_repulsions: FloatArray
    grad_matrixes: FloatArray

    def __init__(self, geometries: list[dict[str, Any]], properties: dict | None = ..., **kwargs: Any) -> None: ...
    def set_repulsion(self, new_repulsion: Any) -> None: ...
    def in_bbox(self, x: Point) -> bool: ...
    def get_dist_matrix(self, scaled: bool = ..., inverted: bool = ...) -> FloatArray: ...
    def get_center_point(self) -> FloatArray: ...
    def squared_dist(  # type: ignore[override]
        self, x: FloatArray, scaled: bool = ..., inverted: bool = ..., return_reference: bool = ..., **kwargs: Any
    ) -> Any: ...
    def repulsion_vector(self, x: FloatArray, min_dist_select: bool = ..., **kwargs: Any) -> FloatArray: ...
    def gradient(self, x: FloatArray, **kwargs: Any) -> FloatArray: ...
    def toRGeoJSON(self) -> RGeoJSONObject: ...

_RGJ_TYPES: dict[str, type]
