"""Type stubs for larp.field.quadtree (compiled from quadtree.pyx)."""

from __future__ import annotations

from types import EllipsisType
from typing import Any, ClassVar

import numpy as np
import numpy.typing as npt

from larp.types import Point

FloatArray = npt.NDArray[np.float64]
IntArray = npt.NDArray[np.int64]

class QuadNode:
    chdToIdx: ClassVar[dict[str, int]]
    nghToIdx: ClassVar[dict[str, int]]

    center_point: FloatArray
    size: float
    leaf: bool
    boundary_zone: int
    boundary_max_range: float
    rgj_idx: IntArray
    rgj_risks: FloatArray
    children: list[QuadNode | None]
    neighbors: list[QuadNode | None]

    def __init__(self, center_point: Point, size: float) -> None: ...
    def __getitem__(self, idx: str | int | tuple | list) -> QuadNode | list[QuadNode | None] | None: ...
    def __setitem__(self, idx: str | int | tuple | list, value: QuadNode) -> None: ...
    def __lt__(self, other: QuadNode) -> bool: ...
    def __hash__(self) -> int: ...
    def get_boundaries(self) -> FloatArray: ...
    def in_bbox(self, points: Point | FloatArray) -> npt.NDArray[np.bool_]: ...
    def get_shared_edge(self, neighbor: QuadNode | None) -> FloatArray | None: ...
    def to_boundary_lines(self, margin: float = ...) -> tuple[FloatArray, FloatArray]: ...

class QuadTree:
    MAX_DEPTH: ClassVar[int]

    field: Any  # larp.field.risk_field.RiskField, kept untyped to avoid a circular import
    min_sector_size: float
    max_sector_size: float
    size: float
    risk_epsilon: float
    conservative_tol: float
    conservative: bool
    root: QuadNode | None
    leaves: set[QuadNode]

    def __init__(
        self,
        field: Any,
        minimum_length_limit: float | None | EllipsisType = ...,
        maximum_length_limit: float = ...,
        risk_epsilon: float = ...,
        conservative_tol: float = ...,
        size: float | None = ...,
        conservative: bool = ...,
        build_tree: bool = ...,
    ) -> None: ...
    def __iter__(self) -> QuadTree: ...
    def __next__(self) -> QuadNode: ...
    def __len__(self) -> int: ...
    def mark_leaf(self, quad: QuadNode) -> None: ...
    def build(self) -> QuadNode: ...
    def to_boundary_lines_collection(self, margin: float = ...) -> list[FloatArray]: ...
    def replace_branch(self, rootquad: QuadNode, child: str, branch: QuadNode | None) -> None: ...
    def get_quad_maximum_range(self) -> FloatArray: ...
    def find_quad(self, x: list[Point] | FloatArray, max_depth: int = ...) -> list[QuadNode | None]: ...
    def find_quads_chain(
        self, x: list[Point] | FloatArray, max_depth: int | None = ...
    ) -> list[list[QuadNode | None]]: ...
    def search_leaves(self, quad: QuadNode | None = ..., max_depth: int | None = ...) -> set[QuadNode]: ...
    def get_quad_zones(self) -> npt.NDArray[np.int_]: ...
    def to_dict(self) -> dict: ...
    def from_dict(self, data: dict) -> None: ...
    def to_image(
        self, return_zone: bool = ..., return_extent: bool = ..., max_depth: int | None = ...
    ) -> FloatArray | tuple[FloatArray, list[float]]: ...
    def quad_to_image(
        self, quad: QuadNode | None = ..., resolution: int = ..., margin: float = ...
    ) -> FloatArray: ...
